[bspwm]

keymap = [
  { keys = ["super+enter"], command = "open termial" },
  { keys = ["super+p"], command = "float termial" },
  { keys = ["super+b"], command = "eww dashboard" },
  { keys = ["super+d"], command = "rofi" },
  { keys = ["super+alt+q"], command = "quit bspwm" },
  { keys = ["super+alt+r"], command = "reload bspwm" },
  { keys = ["super+m"], command = "monocle layout" },
  { keys = ["super+t"], command = "titled state" },
  { keys = ["super+shift+t"], command = "pseudo_titled state" },
  { keys = ["super+shift+q"], command = "close node" },
  { keys = ["super+q"], command = "close node" },
  { keys = ["super+m"], command = "switch tiled and monocle" },
  { keys = ["shift+alt+x"], command = "lock screen" },
]
