#! /bin/bash

disabled=$(dunstctl is-paused)

toggle() {
    dunstctl set-paused toggle
}

icon() {
    # 󰗕
    echo "󰗔"
}

status() {
    bluetooth_status=$(./bluetooth status)
    wifi_status=$(./wifi status)

    if [[ $disabled == "true" ]]; then
        echo "on"
    else
        echo "off"
    fi
}

if [[ $1 == "toggle" ]]; then
    toggle
elif [[ $1 == "icon" ]]; then
    icon
elif [[ $1 == "status" ]]; then
    status
fi
