#! /bin/bash

case "$1" in
    up)
        light -A 2
        ;;
    down)
        light -U 2
        ;;
esac

if [[ $2 == "notify" ]]; then
    strength=$(light -G)
    tag="backlight"
    dunstify -a "changebacklight" -u low --icon=lightbulb -h string:x-dunst-stack-tag:$tag \
        -h int:value:"$strength" "Backlight: $strength"
fi
