#! /bin/sh

xset r rate 300 50

# sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

$HOME/.config/bspwm/switch_monitor

# polybar
$HOME/.config/polybar/launch.sh

# eww widgets
# $HOME/.config/eww/launch.sh
eww daemon -c $HOME/.config/eww/settings

# dunst
# dunst can't not reload configuration automatically
pkill dunst && dunst

# picom
picom -b

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-A-0 I II III IV V VI VII VIII IX X
# bspc monitor eDP I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 12
bspc config normal_border_color \#BABBF1
bspc config active_border_color \#81C8BE
bspc config focused_border_color \#F4B8E4

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding 10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a float_term:float_term state=floating center=true rectangle=1400x800+0+0
bspc rule -a float_contrl:float_control state=floating center=true rectangle=1400x800+0+0
bspc rule -a Clash-verge desktop='^6'

# load apps after initialization
clash-verge
