
[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "Maple Mono NL NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NL NF CN"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Maple Mono NL NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NL NF CN"
style = "Regular"

[font.offset]
x = 0
y = 0

[general]
import = ["/home/tpcad/.config/alacritty/catppuccin-frappe.toml"]
